import { Header } from "../components/Header";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "../components/ui/avatar";
import { ChevronLeft, ChevronRight, Sparkles, Calendar as CalendarIcon, Clock, Lightbulb } from "lucide-react";
import { useState } from "react";
import { format, addDays, startOfWeek, isSameDay } from "date-fns";
import { es } from "date-fns/locale";

interface CalendarEvent {
  id: string;
  title: string;
  date: Date;
  startTime: string;
  duration: number;
  assignee: string;
  avatar: string;
  source: string;
  autoGenerated: boolean;
}

export default function CalendarView() {
  const [currentWeek, setCurrentWeek] = useState(new Date());
  const weekStart = startOfWeek(currentWeek, { weekStartsOn: 1 });

  const events: CalendarEvent[] = [
    {
      id: "1",
      title: "Revisión de diseño UI/UX",
      date: addDays(weekStart, 2),
      startTime: "10:00",
      duration: 2,
      assignee: "María García",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      source: "Reunión de planificación Q1",
      autoGenerated: true,
    },
    {
      id: "2",
      title: "Implementar autenticación MFA",
      date: addDays(weekStart, 3),
      startTime: "14:00",
      duration: 3,
      assignee: "Carlos Ruiz",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
      source: "Reunión de planificación Q1",
      autoGenerated: true,
    },
    {
      id: "3",
      title: "Sprint planning - Backend",
      date: addDays(weekStart, 4),
      startTime: "09:00",
      duration: 1.5,
      assignee: "Laura Martínez",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
      source: "Sesión de estrategia de producto",
      autoGenerated: true,
    },
    {
      id: "4",
      title: "Documentación de API",
      date: addDays(weekStart, 1),
      startTime: "11:00",
      duration: 2,
      assignee: "Laura Martínez",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
      source: "Reunión de planificación Q1",
      autoGenerated: true,
    },
    {
      id: "5",
      title: "Demo para stakeholders",
      date: addDays(weekStart, 5),
      startTime: "16:00",
      duration: 1,
      assignee: "David López",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
      source: "Stand-up diario del equipo",
      autoGenerated: true,
    },
  ];

  const weekDays = Array.from({ length: 7 }, (_, i) => addDays(weekStart, i));
  const hours = Array.from({ length: 12 }, (_, i) => i + 8); // 8am to 8pm

  const getEventsForDay = (day: Date) => {
    return events.filter((event) => isSameDay(event.date, day));
  };

  const aiSuggestions = [
    {
      title: "Optimización detectada",
      description: "Puedes reorganizar 3 tareas para reducir el tiempo total en 4 horas",
    },
    {
      title: "Bloque de enfoque",
      description: "Se recomienda crear un bloque de 3h el miércoles por la mañana para trabajo profundo",
    },
    {
      title: "Carga de trabajo",
      description: "El jueves tiene alta densidad. Considera mover 1 tarea al viernes",
    },
  ];

  return (
    <div className="relative z-[1] min-h-screen app-background">
      <Header />

      <main className="mx-auto max-w-[1600px] px-8 py-8">
        {/* Page Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Calendario inteligente</h1>
            <p className="text-gray-600">
              Tu agenda optimizada automáticamente basada en tus reuniones
            </p>
          </div>
          <Button className="gap-2 bg-indigo-600 hover:bg-indigo-700">
            <Sparkles className="w-4 h-4" />
            Optimizar mi semana
          </Button>
        </div>

        <div className="grid grid-cols-12 gap-6">
          {/* Calendar View */}
          <div className="col-span-9">
            <Card className="border-gray-200">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4">
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => setCurrentWeek(addDays(currentWeek, -7))}
                    >
                      <ChevronLeft className="w-4 h-4" />
                    </Button>
                    <div className="text-center">
                      <h2 className="text-lg font-semibold">
                        {format(weekStart, "MMMM yyyy", { locale: es })}
                      </h2>
                      <p className="text-sm text-gray-500">
                        Semana del {format(weekStart, "d")} al{" "}
                        {format(addDays(weekStart, 6), "d MMMM", { locale: es })}
                      </p>
                    </div>
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={() => setCurrentWeek(addDays(currentWeek, 7))}
                    >
                      <ChevronRight className="w-4 h-4" />
                    </Button>
                  </div>
                  <Badge className="bg-indigo-50 text-indigo-700 border-indigo-200 gap-1">
                    <Sparkles className="w-3 h-3" />
                    5 eventos auto-generados
                  </Badge>
                </div>
              </CardHeader>
              <CardContent>
                {/* Calendar Grid */}
                <div className="border rounded-lg overflow-hidden">
                  {/* Day Headers */}
                  <div className="grid grid-cols-8 bg-gray-50 border-b">
                    <div className="p-3 text-xs font-medium text-gray-500 border-r">Hora</div>
                    {weekDays.map((day) => (
                      <div
                        key={day.toString()}
                        className="p-3 text-center border-r last:border-r-0"
                      >
                        <div className="text-xs font-medium text-gray-500 uppercase">
                          {format(day, "EEE", { locale: es })}
                        </div>
                        <div
                          className={`text-lg font-semibold mt-1 ${
                            isSameDay(day, new Date())
                              ? "text-indigo-600"
                              : "text-gray-900"
                          }`}
                        >
                          {format(day, "d")}
                        </div>
                      </div>
                    ))}
                  </div>

                  {/* Time Grid */}
                  <div className="grid grid-cols-8 divide-y">
                    {hours.map((hour) => (
                      <div key={hour} className="contents">
                        <div className="p-3 text-xs text-gray-500 border-r bg-gray-50">
                          {hour.toString().padStart(2, "0")}:00
                        </div>
                        {weekDays.map((day, dayIndex) => {
                          const dayEvents = getEventsForDay(day).filter((event) => {
                            const eventHour = parseInt(event.startTime.split(":")[0]);
                            return eventHour === hour;
                          });

                          return (
                            <div
                              key={`${day.toString()}-${hour}`}
                              className="p-2 border-r last:border-r-0 min-h-[80px] relative"
                            >
                              {dayEvents.map((event) => (
                                <Card
                                  key={event.id}
                                  className="mb-2 border-l-4 border-l-indigo-600 bg-indigo-50 hover:shadow-md transition-shadow cursor-pointer"
                                >
                                  <CardContent className="p-2">
                                    <div className="flex items-start justify-between gap-2 mb-1">
                                      <p className="text-xs font-medium text-gray-900 line-clamp-2">
                                        {event.title}
                                      </p>
                                      {event.autoGenerated && (
                                        <Badge className="bg-indigo-600 text-white text-[10px] px-1 py-0 h-4">
                                          Auto
                                        </Badge>
                                      )}
                                    </div>
                                    <div className="flex items-center gap-2">
                                      <Avatar className="w-4 h-4">
                                        <AvatarImage src={event.avatar} />
                                        <AvatarFallback className="text-[8px]">
                                          {event.assignee
                                            .split(" ")
                                            .map((n) => n[0])
                                            .join("")}
                                        </AvatarFallback>
                                      </Avatar>
                                      <span className="text-[10px] text-gray-600">
                                        {event.startTime} · {event.duration}h
                                      </span>
                                    </div>
                                  </CardContent>
                                </Card>
                              ))}
                            </div>
                          );
                        })}
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Right Sidebar - AI Planning */}
          <aside className="col-span-3">
            <div className="sticky top-8 space-y-6">
              {/* AI Plan Summary */}
              <Card className="border-indigo-200 bg-gradient-to-br from-indigo-50 to-purple-50">
                <CardHeader className="pb-4">
                  <CardTitle className="flex items-center gap-2 text-lg">
                    <Sparkles className="w-5 h-5 text-indigo-600" />
                    Plan sugerido por IA
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="bg-white/80 rounded-lg p-4 space-y-3">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center">
                        <CalendarIcon className="w-5 h-5 text-indigo-600" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">5 eventos programados</p>
                        <p className="text-xs text-gray-600">Esta semana</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-purple-100 flex items-center justify-center">
                        <Clock className="w-5 h-5 text-purple-600" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">12.5 horas totales</p>
                        <p className="text-xs text-gray-600">Tiempo estimado</p>
                      </div>
                    </div>
                  </div>

                  <div>
                    <h4 className="text-sm font-medium mb-2">Distribución inteligente</h4>
                    <p className="text-xs text-gray-600 leading-relaxed">
                      La IA ha distribuido tus tareas considerando prioridades, dependencias y
                      disponibilidad. Los eventos se agruparon por contexto para maximizar tu
                      productividad.
                    </p>
                  </div>
                </CardContent>
              </Card>

              {/* AI Suggestions */}
              <Card className="border-gray-200">
                <CardHeader className="pb-3">
                  <CardTitle className="flex items-center gap-2 text-sm">
                    <Lightbulb className="w-4 h-4 text-amber-600" />
                    Recomendaciones
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {aiSuggestions.map((suggestion, index) => (
                    <div key={index} className="space-y-1">
                      <p className="text-xs font-medium text-gray-900">{suggestion.title}</p>
                      <p className="text-xs text-gray-600">{suggestion.description}</p>
                    </div>
                  ))}
                </CardContent>
              </Card>

              {/* Event Details */}
              <Card className="border-gray-200">
                <CardHeader className="pb-3">
                  <CardTitle className="text-sm">Detalles de eventos</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {events.slice(0, 3).map((event) => (
                    <Card key={event.id} className="border-l-4 border-l-indigo-600">
                      <CardContent className="p-3">
                        <div className="flex items-start justify-between mb-2">
                          <p className="text-xs font-medium">{event.title}</p>
                          <Badge className="bg-indigo-50 text-indigo-700 border-0 text-[10px] px-1.5 gap-1">
                            <Sparkles className="w-2.5 h-2.5" />
                            Auto
                          </Badge>
                        </div>
                        <div className="space-y-1.5">
                          <div className="flex items-center gap-2">
                            <Avatar className="w-5 h-5">
                              <AvatarImage src={event.avatar} />
                              <AvatarFallback className="text-[8px]">
                                {event.assignee
                                  .split(" ")
                                  .map((n) => n[0])
                                  .join("")}
                              </AvatarFallback>
                            </Avatar>
                            <span className="text-[11px] text-gray-600">{event.assignee}</span>
                          </div>
                          <div className="flex items-center gap-1.5 text-[11px] text-gray-500">
                            <Clock className="w-3 h-3" />
                            {format(event.date, "EEE d MMM", { locale: es })} · {event.startTime} (
                            {event.duration}h)
                          </div>
                          <p className="text-[10px] text-gray-400">Desde: {event.source}</p>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </CardContent>
              </Card>
            </div>
          </aside>
        </div>
      </main>
    </div>
  );
}


