import { useState } from "react";
import { Card, CardContent } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { Input } from "./ui/input";
import { Checkbox } from "./ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "./ui/select";
import {
  Search,
  Download,
  Sparkles,
  X,
  ChevronRight,
  GripVertical,
  Link as LinkIcon,
  CalendarPlus,
  Video,
} from "lucide-react";

interface GanttTask {
  id: number;
  title: string;
  assignee: string;
  avatar: string;
  status: "completed" | "in-progress" | "pending" | "blocked";
  priority: "Alta" | "Media" | "Baja";
  startDate: string;
  endDate: string;
  autoGenerated?: boolean;
  meetingSource?: string;
  progress?: number;
}

export function GanttView() {
  const [viewMode, setViewMode] = useState<"week" | "month">("week");
  const [showDependencies, setShowDependencies] = useState(false);
  const [selectedTask, setSelectedTask] = useState<GanttTask | null>(null);
  const [aiPreviewMode, setAiPreviewMode] = useState(false);

  const ganttTasks: GanttTask[] = [
    {
      id: 1,
      title: "Diseñar sistema de componentes",
      assignee: "Laura Martínez",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
      status: "completed",
      priority: "Alta",
      startDate: "2026-02-15",
      endDate: "2026-03-01",
      autoGenerated: false,
      progress: 100,
    },
    {
      id: 2,
      title: "Implementar nuevos widgets",
      assignee: "Ana Silva",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
      status: "in-progress",
      priority: "Alta",
      startDate: "2026-02-28",
      endDate: "2026-03-05",
      autoGenerated: true,
      meetingSource: "Reunión de planificación Q1",
      progress: 65,
    },
    {
      id: 3,
      title: "Refactorizar API de datos",
      assignee: "David López",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
      status: "in-progress",
      priority: "Media",
      startDate: "2026-03-03",
      endDate: "2026-03-08",
      autoGenerated: false,
      progress: 40,
    },
    {
      id: 4,
      title: "Testing de rendimiento",
      assignee: "Carlos Ruiz",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
      status: "pending",
      priority: "Media",
      startDate: "2026-03-06",
      endDate: "2026-03-12",
      autoGenerated: false,
      progress: 0,
    },
    {
      id: 5,
      title: "Documentación técnica",
      assignee: "María García",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      status: "pending",
      priority: "Baja",
      startDate: "2026-03-10",
      endDate: "2026-03-14",
      autoGenerated: true,
      meetingSource: "Sprint Planning - Sprint 1",
      progress: 0,
    },
    {
      id: 6,
      title: "Configurar CI/CD pipeline",
      assignee: "David López",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
      status: "pending",
      priority: "Alta",
      startDate: "2026-03-08",
      endDate: "2026-03-11",
      autoGenerated: false,
      progress: 0,
    },
    {
      id: 7,
      title: "Pruebas de integración",
      assignee: "Ana Silva",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop",
      status: "blocked",
      priority: "Alta",
      startDate: "2026-03-09",
      endDate: "2026-03-13",
      autoGenerated: false,
      progress: 20,
    },
    {
      id: 8,
      title: "Preparar demo para stakeholders",
      assignee: "María García",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      status: "pending",
      priority: "Media",
      startDate: "2026-03-12",
      endDate: "2026-03-15",
      autoGenerated: true,
      meetingSource: "Review de diseño UI/UX",
      progress: 0,
    },
  ];

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "Alta":
        return "bg-red-100 text-red-800 border-red-200";
      case "Media":
        return "bg-yellow-100 text-yellow-800 border-yellow-200";
      case "Baja":
        return "bg-green-100 text-green-800 border-green-200";
      default:
        return "bg-gray-100 text-gray-800 border-gray-200";
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "completed":
        return "bg-green-100 text-green-800 border-0";
      case "in-progress":
        return "bg-blue-100 text-blue-800 border-0";
      case "pending":
        return "bg-gray-100 text-gray-800 border-0";
      case "blocked":
        return "bg-red-100 text-red-800 border-0";
      default:
        return "bg-gray-100 text-gray-800 border-0";
    }
  };

  const getStatusLabel = (status: string) => {
    switch (status) {
      case "completed":
        return "Completada";
      case "in-progress":
        return "En progreso";
      case "pending":
        return "Pendiente";
      case "blocked":
        return "Bloqueada";
      default:
        return status;
    }
  };

  // Calculate bar position and width for Gantt chart
  const getBarStyle = (startDate: string, endDate: string) => {
    const projectStart = new Date("2026-02-15");
    const projectEnd = new Date("2026-03-15");
    const taskStart = new Date(startDate);
    const taskEnd = new Date(endDate);

    const totalDuration = projectEnd.getTime() - projectStart.getTime();
    const taskStartOffset = taskStart.getTime() - projectStart.getTime();
    const taskDuration = taskEnd.getTime() - taskStart.getTime();

    const left = (taskStartOffset / totalDuration) * 100;
    const width = (taskDuration / totalDuration) * 100;

    return { left: `${left}%`, width: `${width}%` };
  };

  // Check if today falls within the project timeline
  const getTodayPosition = () => {
    const projectStart = new Date("2026-02-15");
    const projectEnd = new Date("2026-03-15");
    const today = new Date("2026-03-04"); // Mock today for demo

    const totalDuration = projectEnd.getTime() - projectStart.getTime();
    const todayOffset = today.getTime() - projectStart.getTime();

    return (todayOffset / totalDuration) * 100;
  };

  const getBarColor = (status: string) => {
    switch (status) {
      case "completed":
        return "bg-green-500";
      case "in-progress":
        return "bg-blue-500";
      case "pending":
        return "bg-gray-300";
      case "blocked":
        return "bg-red-400";
      default:
        return "bg-gray-300";
    }
  };

  return (
    <div className="space-y-6">
      {/* AI Preview Banner */}
      {aiPreviewMode && (
        <Card className="border-indigo-200 bg-indigo-50">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Sparkles className="w-5 h-5 text-indigo-600" />
                <p className="text-sm font-medium text-indigo-900">
                  La IA reorganizó tareas para evitar solapes y respetar dependencias
                </p>
              </div>
              <div className="flex items-center gap-2">
                <Button size="sm" variant="outline" onClick={() => setAiPreviewMode(false)}>
                  Revertir
                </Button>
                <Button size="sm" className="bg-indigo-600 hover:bg-indigo-700" onClick={() => setAiPreviewMode(false)}>
                  Aceptar cambios
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Toolbar */}
      <Card className="border-gray-200">
        <CardContent className="p-4">
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              {/* View Mode Selector */}
              <div className="flex items-center gap-1 bg-gray-100 rounded-lg p-1">
                <Button
                  size="sm"
                  variant={viewMode === "week" ? "default" : "ghost"}
                  className={`h-8 ${viewMode === "week" ? "bg-white shadow-sm" : ""}`}
                  onClick={() => setViewMode("week")}
                >
                  Semana
                </Button>
                <Button
                  size="sm"
                  variant={viewMode === "month" ? "default" : "ghost"}
                  className={`h-8 ${viewMode === "month" ? "bg-white shadow-sm" : ""}`}
                  onClick={() => setViewMode("month")}
                >
                  Mes
                </Button>
              </div>

              <Button size="sm" variant="outline">
                Hoy
              </Button>

              {/* Show Dependencies Toggle */}
              <div className="flex items-center gap-2 px-3 py-2 border border-gray-200 rounded-lg">
                <Checkbox
                  id="dependencies"
                  checked={showDependencies}
                  onCheckedChange={(checked) => setShowDependencies(checked as boolean)}
                />
                <label htmlFor="dependencies" className="text-sm cursor-pointer">
                  Mostrar dependencias
                </label>
              </div>

              {/* Filters */}
              <Select defaultValue="all-assignee">
                <SelectTrigger className="w-[160px] h-9">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all-assignee">Todos</SelectItem>
                  <SelectItem value="maria">María</SelectItem>
                  <SelectItem value="carlos">Carlos</SelectItem>
                  <SelectItem value="laura">Laura</SelectItem>
                  <SelectItem value="david">David</SelectItem>
                  <SelectItem value="ana">Ana</SelectItem>
                </SelectContent>
              </Select>

              <Select defaultValue="all-status">
                <SelectTrigger className="w-[160px] h-9">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all-status">Todos los estados</SelectItem>
                  <SelectItem value="pending">Pendiente</SelectItem>
                  <SelectItem value="in-progress">En progreso</SelectItem>
                  <SelectItem value="completed">Completada</SelectItem>
                  <SelectItem value="blocked">Bloqueada</SelectItem>
                </SelectContent>
              </Select>

              <Select defaultValue="all-priority">
                <SelectTrigger className="w-[160px] h-9">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all-priority">Todas las prioridades</SelectItem>
                  <SelectItem value="high">Alta</SelectItem>
                  <SelectItem value="medium">Media</SelectItem>
                  <SelectItem value="low">Baja</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-center gap-2">
              {/* Search */}
              <div className="relative">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                <Input placeholder="Buscar tarea" className="pl-9 w-[200px] h-9" />
              </div>

              <Button size="sm" variant="outline" className="gap-2">
                <Download className="w-4 h-4" />
                Exportar
              </Button>

              <Button
                size="sm"
                className="gap-2 bg-indigo-600 hover:bg-indigo-700"
                onClick={() => setAiPreviewMode(!aiPreviewMode)}
              >
                <Sparkles className="w-4 h-4" />
                Optimizar plan (IA)
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Gantt Chart */}
      <div className="flex gap-0 border border-gray-200 rounded-lg bg-white overflow-hidden">
        {/* Left Panel - Task List */}
        <div className="w-[500px] border-r border-gray-200">
          {/* Header */}
          <div className="h-12 bg-gray-50 border-b border-gray-200 px-4 flex items-center text-xs font-semibold text-gray-600 uppercase">
            Tarea
          </div>

          {/* Tasks */}
          <div className="divide-y divide-gray-100">
            {ganttTasks.map((task) => (
              <div
                key={task.id}
                className={`h-14 px-4 flex items-center gap-3 hover:bg-gray-50 cursor-pointer transition-colors ${
                  selectedTask?.id === task.id ? "bg-indigo-50" : ""
                }`}
                onClick={() => setSelectedTask(task)}
              >
                <Checkbox checked={task.status === "completed"} />
                <GripVertical className="w-4 h-4 text-gray-400" />
                
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-gray-900 truncate">{task.title}</p>
                  {task.autoGenerated && (
                    <Badge variant="secondary" className="text-xs bg-indigo-50 text-indigo-700 border-0 mt-1">
                      Auto-generada
                    </Badge>
                  )}
                </div>

                <Avatar className="w-7 h-7">
                  <AvatarImage src={task.avatar} alt={task.assignee} />
                  <AvatarFallback className="text-xs">
                    {task.assignee.split(" ").map((n) => n[0]).join("")}
                  </AvatarFallback>
                </Avatar>

                <Badge className={getStatusColor(task.status)} variant="secondary">
                  <div className="w-1.5 h-1.5 rounded-full bg-current mr-1.5" />
                  {getStatusLabel(task.status)}
                </Badge>

                <Badge className={getPriorityColor(task.priority)}>
                  {task.priority}
                </Badge>
              </div>
            ))}
          </div>
        </div>

        {/* Right Panel - Timeline */}
        <div className="flex-1 overflow-x-auto">
          {/* Timeline Header */}
          <div className="h-12 bg-gray-50 border-b border-gray-200 px-4 flex items-center">
            <div className="relative w-full">
              <div className="flex justify-between text-xs font-semibold text-gray-600">
                <span>15 Feb</span>
                <span>22 Feb</span>
                <span>1 Mar</span>
                <span>8 Mar</span>
                <span>15 Mar</span>
              </div>
            </div>
          </div>

          {/* Timeline Bars */}
          <div className="relative">
            {/* Today Line */}
            <div
              className="absolute top-0 bottom-0 w-0.5 bg-indigo-600 z-10"
              style={{ left: `${getTodayPosition()}%` }}
            >
              <div className="absolute -top-2 left-1/2 -translate-x-1/2 bg-indigo-600 text-white text-xs px-2 py-0.5 rounded whitespace-nowrap">
                Hoy
              </div>
            </div>

            {/* Task Bars */}
            {ganttTasks.map((task, index) => {
              const barStyle = getBarStyle(task.startDate, task.endDate);
              return (
                <div
                  key={task.id}
                  className={`h-14 border-b border-gray-100 relative px-4 flex items-center ${
                    selectedTask?.id === task.id ? "bg-indigo-50" : ""
                  }`}
                >
                  <div className="relative w-full h-8">
                    <div
                      className={`absolute h-8 rounded ${getBarColor(task.status)} transition-all ${
                        aiPreviewMode && (index === 1 || index === 2) ? "ring-2 ring-indigo-400" : ""
                      }`}
                      style={barStyle}
                    >
                      {/* Progress background */}
                      {task.progress !== undefined && task.progress > 0 && task.status !== "completed" && (
                        <div 
                          className="absolute inset-0 bg-white/20 rounded" 
                          style={{ width: `${100 - task.progress}%`, right: 0, left: 'auto' }}
                        />
                      )}
                      <div className="relative h-full flex items-center justify-between px-2">
                        <span className="text-xs text-white font-medium truncate flex-1">
                          {task.title}
                        </span>
                        {task.progress !== undefined && task.progress > 0 && (
                          <span className="text-xs text-white/90 font-medium ml-2">
                            {task.progress}%
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Dependency Lines */}
                    {showDependencies && index > 0 && index < 3 && (
                      <svg className="absolute top-0 left-0 w-full h-full pointer-events-none" style={{ overflow: "visible" }}>
                        <path
                          d={`M ${parseFloat(barStyle.left || "0")} 16 L ${parseFloat(barStyle.left || "0") - 20} 16`}
                          stroke="#9CA3AF"
                          strokeWidth="1.5"
                          fill="none"
                          markerEnd="url(#arrowhead)"
                        />
                        <defs>
                          <marker
                            id="arrowhead"
                            markerWidth="10"
                            markerHeight="10"
                            refX="5"
                            refY="3"
                            orient="auto"
                          >
                            <polygon points="0 0, 10 3, 0 6" fill="#9CA3AF" />
                          </marker>
                        </defs>
                      </svg>
                    )}

                    {/* Milestone */}
                    {task.id === 2 && (
                      <div
                        className="absolute top-1/2 -translate-y-1/2 w-3 h-3 bg-purple-600 rotate-45"
                        style={{ left: `calc(${barStyle.left} + ${barStyle.width})` }}
                      />
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Task Details Drawer */}
      {selectedTask && (
        <Card className="border-gray-200 fixed right-8 top-24 w-[400px] shadow-xl z-50">
          <CardContent className="p-0">
            <div className="p-4 border-b border-gray-200 flex items-center justify-between bg-gray-50">
              <h3 className="font-semibold text-gray-900">Detalles de la tarea</h3>
              <Button
                variant="ghost"
                size="sm"
                className="h-8 w-8 p-0"
                onClick={() => setSelectedTask(null)}
              >
                <X className="w-4 h-4" />
              </Button>
            </div>

            <div className="p-4 space-y-4">
              <div>
                <label className="text-xs font-medium text-gray-600 block mb-1">
                  Título
                </label>
                <Input defaultValue={selectedTask.title} className="h-9" />
              </div>

              <div>
                <label className="text-xs font-medium text-gray-600 block mb-1">
                  Responsable
                </label>
                <Select defaultValue={selectedTask.assignee}>
                  <SelectTrigger className="h-9">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="María García">María García</SelectItem>
                    <SelectItem value="Carlos Ruiz">Carlos Ruiz</SelectItem>
                    <SelectItem value="Laura Martínez">Laura Martínez</SelectItem>
                    <SelectItem value="David López">David López</SelectItem>
                    <SelectItem value="Ana Silva">Ana Silva</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-600 block mb-1">
                    Estado
                  </label>
                  <Select defaultValue={selectedTask.status}>
                    <SelectTrigger className="h-9">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="pending">Pendiente</SelectItem>
                      <SelectItem value="in-progress">En progreso</SelectItem>
                      <SelectItem value="completed">Completada</SelectItem>
                      <SelectItem value="blocked">Bloqueada</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <label className="text-xs font-medium text-gray-600 block mb-1">
                    Prioridad
                  </label>
                  <Select defaultValue={selectedTask.priority}>
                    <SelectTrigger className="h-9">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Alta">Alta</SelectItem>
                      <SelectItem value="Media">Media</SelectItem>
                      <SelectItem value="Baja">Baja</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-600 block mb-1">
                    Fecha inicio
                  </label>
                  <Input type="date" defaultValue={selectedTask.startDate} className="h-9" />
                </div>

                <div>
                  <label className="text-xs font-medium text-gray-600 block mb-1">
                    Deadline
                  </label>
                  <Input type="date" defaultValue={selectedTask.endDate} className="h-9" />
                </div>
              </div>

              <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                <span className="text-sm text-gray-700">Añadir al calendario</span>
                <Checkbox />
              </div>

              {selectedTask.autoGenerated && selectedTask.meetingSource && (
                <div className="p-3 bg-indigo-50 rounded-lg border border-indigo-100">
                  <div className="flex items-start gap-2">
                    <Video className="w-4 h-4 text-indigo-600 mt-0.5" />
                    <div className="flex-1">
                      <p className="text-xs font-medium text-indigo-900 mb-1">
                        Creada desde reunión
                      </p>
                      <a href="#" className="text-xs text-indigo-700 hover:text-indigo-800 flex items-center gap-1">
                        {selectedTask.meetingSource}
                        <ChevronRight className="w-3 h-3" />
                      </a>
                    </div>
                  </div>
                </div>
              )}
            </div>

            <div className="p-4 border-t border-gray-200 flex gap-2">
              <Button variant="outline" className="flex-1" onClick={() => setSelectedTask(null)}>
                Cancelar
              </Button>
              <Button className="flex-1 bg-indigo-600 hover:bg-indigo-700">
                Guardar cambios
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
